# Generated by Django 2.2.6 on 2019-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
