# Generated by Django 2.2.6 on 2019-11-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbot', '0002_auto_20191112_1911'),
        ('vbot', '0002_viberuser_is_active'),
    ]

    operations = [
    ]
